# Generated by Django 4.2 on 2023-06-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bg_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='bride_story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('story', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='groom_story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('story', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brides_name', models.CharField(max_length=30)),
                ('grooms_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='main_story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fast_meet', models.CharField(max_length=150)),
                ('he_proposed', models.CharField(max_length=150)),
                ('love_story', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='prog_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_name', models.CharField(max_length=30)),
                ('time', models.TimeField()),
                ('discription', models.TextField()),
                ('bg_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
