# Generated by Django 4.2.1 on 2023-06-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grooms_name', models.CharField(max_length=30)),
                ('grooms_image', models.ImageField(upload_to='')),
                ('grooms_story', models.TextField(blank=True, null=True)),
                ('brides_name', models.CharField(max_length=30)),
                ('brides_image', models.ImageField(upload_to='')),
                ('brides_story', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='bride_story',
        ),
        migrations.DeleteModel(
            name='groom_story',
        ),
        migrations.DeleteModel(
            name='main_story',
        ),
        migrations.AlterField(
            model_name='prog_detail',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
