# Generated by Django 4.2.1 on 2023-06-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wed', '0002_story_delete_bride_story_delete_groom_story_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fast_meet', models.CharField(max_length=150)),
                ('he_proposed', models.CharField(max_length=150)),
                ('love_story', models.CharField(max_length=150)),
            ],
        ),
    ]
