# Generated by Django 4.2.1 on 2023-06-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wed', '0004_blog_single_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bg_img',
        ),
        migrations.AddField(
            model_name='intro',
            name='back_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
