# Generated by Django 4.2.1 on 2023-06-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wed', '0005_delete_bg_img_intro_back_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='ceremony',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
