# Generated by Django 4.2.1 on 2023-06-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wed', '0006_intro_ceremony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='grooms_image',
            field=models.ImageField(upload_to='Story'),
        ),
    ]
