# Generated by Django 4.2.1 on 2023-06-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wed', '0008_alter_main_story_fast_meet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='discription',
            field=models.TextField(),
        ),
    ]
