# Generated by Django 4.2 on 2023-06-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wed', '0012_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='accommodation')),
            ],
        ),
    ]
