# Generated by Django 4.2.1 on 2023-06-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wed', '0013_accommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
