# Generated by Django 4.2.1 on 2023-06-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wed', '0014_alter_accommodation_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
