# Generated by Django 4.2.1 on 2023-06-07 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wed', '0016_alter_blog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceremony_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='intro',
            name='ceremony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wed.ceremony'),
        ),
    ]
